### ISSUE TITLE
Request to replace this library

### ISSUE THREAD

**Issue by z3t0** [arduino-libraries/RobotIRremote#2]
Hi,

I would like to propose that this library be replaced by the more feature filled Arduino-IRremote.

[Project](https://github.com/z3t0/Arduino-IRremote)
[Issue](https://github.com/z3t0/Arduino-IRremote/issues/431#issuecomment-218668143)

**Comment by cmaglie** [comment]
@z3t0 
thank you very much for your proposal, anyway I think it's better to just rename the include inside the current library (I've already did it, and the change will be part of the next IDE release), so they don't interfere anymore with your library.
This is for two reasons:

1) the RobotIRRemote is a stripped down version of IRRemote. This was probably done to reduce the size of the library to fit in the limited memory of the Atmega32u4 together with a bunch of other heavy libraries. I down know if replacing it with a full version would still allow to fit
2) bundling the libraries in the IDE is a sort of "curse", becuase the version bundled becomes "viral". It may be ok if there are no problems, but if a bug is present in the version bundled in the IDE, it will become a real problem (that's the reason why we are not adding new bundled libraries anymore).

I'm closing this issue now, if you have any comment or if I missed something, I'm happy to discuss it further.

Thanks!

**Comment by z3t0** [comment]
I understand, thanks for the response.

Thanks,
Rafi Khan
